[book]
authors = ["Tools for Humanity Applied Research Team"]
language = "en"
src = "src"
title = "The Remainder Book"

# https://github.com/lzanini/mdbook-katex
[preprocessor.katex]
after = ["links"]
macros = "src/macros.txt"
